name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'LICENSE.txt'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'LICENSE.txt'

jobs:

  build-and-test:

    name: Build & Test

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

    runs-on: ubuntu-latest
